### ISSUE TITLE
대관현황 조회 방식

### ISSUE THREAD

**Issue by eunddodi** [ANTARES-KOR/yonsei-space-system#44]
### 요구사항분석

사용자가 강의실을 선택하면 해당 강의실의 대관현황이 테이블에 표시된다.

### atom, selector, interface 정의

**대관현황조회와 관련된 상태를 다음과 같이 정의**

- 선택한 건물:  UI에만 영향 → 전역 상태로 관리할 필요 없음
- 선택한 강의실 : 전역 상태 → atom `lectureRoomChoiceState`
- 강의실 대관 현황: `선택한 강의실` 값에 의존한다. → selector `reservationStatusState`

*selector: atom/다른 selector에 의존한다. dependencies에 변화가 생기면 값을 re-evaluate해 새로운 값을 리턴한다. dependencies가 동일하다면 캐싱된 값을 리턴한다.

```mermaid
flowchart LR
Btn[강의실 선택 Btn 클릭] --> |update| A(lectureRoomChoiceState) --> |update| B(reservationStatusState) --> |반영| C(대관 현황 Table)
```

```tsx
// interfaces.ts

interface SingleReservation { // 개별 예약 
  id: string;
  title: string;
  start: string;
  end: string;
  date: string;
  url: string;
  allDay: boolean;
}

interface ReservationPerDay { // 날짜별 예약
	date: string;
	reservations: SingleReservation[];
}

type ReservationsPerRoom = ReservationPerDay[]; // 강의실별 예약

type RoomUIDs = 555|704|14151|14152|14158|14159;
```

```tsx
const lectureRoomChoiceState = atom<RoomUIDs|null>({
	key: 'lectureRoomChoiceState',
	default: null,
});

const reservationStatusState = selector<ReservationsPerRoom>({
	key: 'reservationStatusState',
	get: async ({get}) => {
		const res = await YSSApi.getReservations({
			// building:,
			room: get(lectureRoomChoiceState),
		});
		return res;
	}
});
```

```tsx
// constants.ts

const lectureRoomsList = [
  { building: '제1공학관', rooms: ['공A546'] },
  { building: '제4공학관', rooms: ['공D403', '공D404', '공D503'] },
];
```

- 우선 지금은 기존에 사용하던 강의실 목록을 사용 → 이후에 API 응답으로 교체 예정
- `BuildingID`- `RoomUID` 2중으로 할 필요 없이 RoomUID만으로 강의실 구분

### React.Suspense 활용

React.Suspense로 `Table` 컴포넌트를 감싸 `reservationStatusState` 의 async 요청이 완료될 때까지 loading UI를 렌더링한다. recoil을 사용하면 suspense를 throw하는 별도의 함수 없이 Suspense를 사용할 수 있다. 

### 논의해야 할 사항

- `RoomUID`- `강의실 이름` 매핑 정보 FE/BE 중 어디에 저장? API 응답으로 RoomUID만 줄건지 건물 및 강의실 이름까지 줄건지. 어떤 모양의 객체로 주고받을 지 논의 필요!
- 캐싱: 해당 강의실 대관현황을 조회한 적이 있을 경우 이를 우선적으로 보여주고, API 요청이 완료되면 최신 정보로 업데이트.
    → 어떻게 구현?

**Comment by eunddodi** [comment]
더 고민하기보다 얼른 공개하고 논의하는 게 나을 거 같아서 일단 공개^_^...

**Comment by ANTARES-KOR** [comment]
괜찮은데?

API Response는 이런 형태로 보내면 어떨까?
```typescript
{
	building_name : "제1공학관"
	rooms : {
		room_name: "공 A546",
		room_uid: 555
	}[]
}[]
```

**Comment by eunddodi** [comment]
> 

굿굿 좋아용
대관현황조회 요청할 때는 어떤 식으로 보내면 좋을까 room_uid만?

**Comment by ANTARES-KOR** [comment]
`room_uid` 만 보내면 될듯!

**Comment by eunddodi** [comment]
확인~~ 꺄 재밌겠단

**Comment by eunddodi** [comment]
> `room_uid` 만 보내면 될듯!

시간 나실 때 API 수정 부탁드립니당~~~
