### ISSUE TITLE
특정 날짜의 대관 예약이 조회되지 않는 문제

### ISSUE THREAD

**Issue by eunddodi** [ANTARES-KOR/yonsei-space-system#50]
### 정상 작동 시 조회되어야 하는 날짜
* 2022/09/24
* 2022/10/01

이 중 2022/10/01이 조회되지 않는다. 오른쪽의 console.log를 보면 응답 데이터에도 2022/10/01이 없는 것을 확인할 수 있다.

<img width="1440" alt="스크린샷 2022-09-19 오후 10 23 23" src="https://user-images.githubusercontent.com/87167786/191032238-ade6f04d-6fb2-4480-a0cc-03bac88e3952.png">

### 실제 대관현황조회 사이트에서 확인

실제 대관현황조회 사이트의 월간뷰와 주간뷰에는 10/1일에 예약이 존재하는 것으로 확인된다.

<img width="1440" alt="스크린샷 2022-09-19 오후 10 24 50" src="https://user-images.githubusercontent.com/87167786/191032660-568dd98f-9729-41e7-9bdd-2dcfee0e05dd.png">

<img width="1295" alt="스크린샷 2022-09-19 오후 10 25 17" src="https://user-images.githubusercontent.com/87167786/191032670-5621e781-1d74-4dae-9d6a-6335f3fdac62.png">

한 번 확인이 필요해 보입니다!!

**Comment by eunddodi** [comment]
참고로 D404가 아닌 강의실은 문제 없이 작동했어요!

**Comment by ANTARES-KOR** [comment]
헉

**Comment by eunddodi** [comment]
실제 공간대관시스템 네트워크 창에선 해당 날짜가 잘 뜨는 거 보니까 가져올 때나 가져와서 필터링할 때 뭔가 문제가 생기는 것 같아여

**Comment by ANTARES-KOR** [comment]
오늘 저녁에 작업하도록 하겠숨니닷

**Comment by eunddodi** [comment]
넹 감삼닷~~~

2022년 9월 22일 (목) 오후 12:27, Hyeokjun seo ***@***.***>님이 작성:
